# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68adbe11cf743939b7b3bf18582d97c16cdf5e614e5083c59cbf03e15556b3635c0b864729d8fe27b09e7a1c5927b33c9d60bdb3543ee705a270f71085fa5717

test:
  secret_key_base: d7b818911994f86d564720ee269efc950cee1d010f12feba9c90e202b85677affb64e2d57064066cd6d885156ef23c41447dcaf064ad817272888ff01a82129c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
